import type { ICard } from "./cards.types";
import { EnumTypeCard } from "./constants";

export const RUS_CARDS: ICard[] = [
  {
    name: "Домовой",
    health: 2,
    mana: 1,
    attack: 2,
    type: EnumTypeCard.RANGE_ATTACK,
    imageUrl: "./cards/rusy/Domovoy.avif",
  },
  {
    name: "Свинопас",
    health: 3,
    mana: 1,
    attack: 1,
    imageUrl: "./cards/rusy/Demka-svinopas.avif",
  },
  {
    name: "Мотыгина",
    health: 2,
    mana: 1,
    attack: 2,
    imageUrl: "./cards/rusy/SteshaMotyga.avif",
  },
  {
    name: "Пряжница",
    health: 3,
    mana: 2,
    attack: 2,
    type: EnumTypeCard.RANGE_ATTACK,
    imageUrl: "./cards/rusy/Yaromira.avif",
  },
  {
    name: "Грибослав",
    health: 5,
    mana: 2,
    attack: 2,
    imageUrl: "./cards/rusy/Griboslav.avif",
  },
  {
    name: "Травница",
    health: 3,
    mana: 2,
    attack: 2,
    type: EnumTypeCard.RANGE_ATTACK,
    imageUrl: "./cards/rusy/Travnica.avif",
  },
  {
    name: "Рубослав",
    health: 4,
    mana: 3,
    attack: 2,
    type: EnumTypeCard.FAST_ATTACK,
    imageUrl: "./cards/rusy/RyboSlav.avif",
  },
    {
    name: "Репова",
    health: 5,
    mana: 3,
    attack: 2,
    imageUrl: "./cards/rusy/repovna.avif",
  },
  {
    name: "Лукослав",
    health: 3,
    mana: 3,
    attack: 4,
    type: EnumTypeCard.RANGE_ATTACK,
    imageUrl: "./cards/rusy/Lykoslav.avif",
  },
  {
    name: "БаноСерк",
    health: 3,
    mana: 3,
    attack: 5,
    type: EnumTypeCard.FAST_ATTACK,
    imageUrl: "./cards/rusy/bannyiBersrk.avif",
  },
  {
    name: "БараноБой",
    health: 4,
    mana: 2,
    attack: 2,
    type: EnumTypeCard.FAST_ATTACK,
    imageUrl: "./cards/rusy/BaranoBoy.avif",
  },
  {
    name: "Леший",
    health: 6,
    mana: 5,
    attack: 2,
    type: EnumTypeCard.TAUNT,
    imageUrl: "./cards/rusy/Leshiy.avif",
  },
  {
    name: "Староста",
    health: 5,
    mana: 5,
    attack: 4,
     type: EnumTypeCard.TAUNT,
    imageUrl: "./cards/rusy/Starosta.avif",
  },
  {
    name: "Коростель",
    health: 5,
    mana: 5,
    attack: 5,
    imageUrl: "./cards/rusy/crex.avif",
  },
];
